workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"'

stages:
  - build

build-docker:
  tags:
    - kicad-dind
  stage: build
  image: docker:28
  services:
    - docker:28-dind
  before_script:
    - apk update && apk add --no-cache patch curl
    - curl -LO https://github.com/peak/s5cmd/releases/download/v2.0.0/s5cmd_2.0.0_Linux-64bit.tar.gz
    - mkdir s5cmd
    - tar -xvf ./s5cmd_2.0.0_Linux-64bit.tar.gz -C s5cmd
    - export AWS_ACCESS_KEY_ID=$KICAD_CI_R2_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$KICAD_CI_R2_ACCESS_KEY
    - export S3_ENDPOINT_URL=$KICAD_CI_R2_ENDPOINT

  script:
    - git clone --depth=1 https://gitlab.com/kicad/code/kicad.git
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-symbols.git
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-footprints.git
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-templates.git
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-packages3D.git
    - git clone --depth=1 https://git.code.sf.net/p/ngspice/ngspice.git --branch=ngspice-44.2
    - git clone --depth=1 https://github.com/Open-Cascade-SAS/OCCT.git --branch=V7_8_0
    - patch -d OCCT -p1 < ./patch/0001-occt-tbb-1.diff

    # Use Dmitrii's fork of appimage-builder until the fix is merged
    - |
      git clone https://github.com/sethhillbrand/appimage-builder.git && \
      git --work-tree=./appimage-builder --git-dir=./appimage-builder/.git checkout fix-packaging-version-parse
    - |
      # --build-context packages3d-src=kicad-packages3D
      docker buildx build \
        --progress=plain \
        --build-context kicad-src=kicad \
        --build-context symbols-src=kicad-symbols \
        --build-context footprints-src=kicad-footprints \
        --build-context templates-src=kicad-templates \
        --build-context ngspice-src=ngspice \
        --build-context occt-src=OCCT \
        --build-context appimage-builder-src=appimage-builder \
        --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 \
        --build-arg KICAD_BUILD_MAJVERSION=9 \
        --build-arg KICAD_BUILD_RELEASE=nightly-$(date +%Y%m%d) \
        --platform linux/amd64 \
        --target appimage -o type=local,dest=. \
        -f Dockerfile .
    - s5cmd/s5cmd cp ./*.AppImage s3://$KICAD_CI_R2_BUCKET/appimage/

