workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"'

variables:
  KICAD_BUILD_TYPE: ${KICAD_BUILD_TYPE:-"Nightly"}
  KICAD_BRANCH: ${KICAD_BRANCH:-"master"}
  KICAD_BUILD_RELEASE: ${KICAD_BUILD_RELEASE:-"nightly-$(date +%Y%m%d)"}
  # Version pins for reproducible builds
  WX_VERSION: "3.2.8.1"
  OCCT_VERSION: "V7_9_1"
  WXPYTHON_VERSION: "4.2.3"
  NGSPICE_VERSION: "44.2"
  S5CMD_VERSION: "2.0.0"
  # Docker TLS configuration for buildx
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - base
  - deps
  - build
  - upload

# ============================================================================
# SHARED RULES AND TEMPLATES
# ============================================================================

# Base rules for foundational jobs (schedule: always, manual: manual)
.base_rules: &base_rules
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual

# Standard dependency rules (always run when dependencies succeed)
.dependency_rules: &dependency_rules
  stage: deps
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
      allow_failure: true
      needs: []
    - when: on_success


# ============================================================================
# BUILD JOBS
# ============================================================================

default:
  tags:
    - kicad-dind
  image: docker:28
  services:
    - docker:28-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker context create ki-builder
    - docker buildx create ki-builder --driver docker-container --use
    - docker buildx inspect --bootstrap

# Base image - foundational dependencies
build-base:
  <<: *base_rules
  stage: base
  script:
    - BASE_TAG="base-$(date +%Y%m%d)-$CI_COMMIT_SHORT_SHA"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE/base:$BASE_TAG"
    # Check if we need to rebuild
    - |
      if docker manifest inspect $CI_REGISTRY_IMAGE/base:latest >/dev/null 2>&1 && [ "$FORCE_REBUILD" != "true" ]; then
        echo "Base image exists and no forced rebuild, skipping"
        exit 0
      fi
    - docker build -t $IMAGE_NAME -f docker/Dockerfile.base .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/base:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/base:latest

# wxWidgets - version-pinned rebuild
build-wx:
  <<: *dependency_rules
  script:
    - WX_TAG="wx-$WX_VERSION"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE/wx:$WX_TAG"
    # Check if this version already exists
    - |
      if docker manifest inspect $IMAGE_NAME >/dev/null 2>&1 && [ "$FORCE_REBUILD" != "true" ]; then
        echo "wxWidgets $WX_VERSION already built, syncing latest tag (remote)"
        docker buildx imagetools create --tag "$CI_REGISTRY_IMAGE/wx:latest" "$IMAGE_NAME"
        exit 0
      fi
    - docker build --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:latest --build-arg WX_VERSION=$WX_VERSION -t $IMAGE_NAME -f docker/Dockerfile.wx .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/wx:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/wx:latest

# wxPython - depends on wx
build-wxpython:
  stage: deps
  needs: ["build-wx"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: on_success
  script:
    - WXPY_TAG="wxpython-$WXPYTHON_VERSION"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE/wxpython:$WXPY_TAG"
    # Check if this version already exists
    - |
      if docker manifest inspect $IMAGE_NAME >/dev/null 2>&1 && [ "$FORCE_REBUILD" != "true" ]; then
        echo "wxPython $WXPYTHON_VERSION already built, syncing latest tag (remote)"
        docker buildx imagetools create --tag "$CI_REGISTRY_IMAGE/wxpython:latest" "$IMAGE_NAME"
        exit 0
      fi
    - docker build --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:latest --build-arg WX_IMAGE=$CI_REGISTRY_IMAGE/wx:latest --build-arg WXPYTHON_VERSION=$WXPYTHON_VERSION -t $IMAGE_NAME -f docker/Dockerfile.wxpython .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/wxpython:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/wxpython:latest

# OCCT - version-pinned rebuild
build-occt:
  <<: *dependency_rules
  script:
    - OCCT_TAG="occt-$OCCT_VERSION"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE/occt:$OCCT_TAG"
    # Check if this version already exists
    - |
      if docker manifest inspect $IMAGE_NAME >/dev/null 2>&1 && [ "$FORCE_REBUILD" != "true" ]; then
        echo "OCCT $OCCT_VERSION already built, syncing latest tag (remote)"
        docker buildx imagetools create --tag "$CI_REGISTRY_IMAGE/occt:latest" "$IMAGE_NAME"
        exit 0
      fi
    - git clone --depth=1 --branch=${OCCT_BRANCH:-$OCCT_VERSION} --single-branch --filter=blob:none https://github.com/Open-Cascade-SAS/OCCT.git occt || exit 1
    - docker build --build-context occt-src=occt --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:latest -t $IMAGE_NAME -f docker/Dockerfile.occt .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/occt:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/occt:latest

# ngspice - git hash-based rebuild
build-ngspice:
  <<: *dependency_rules
  script:
    - NGSPICE_TAG="ngspice-$NGSPICE_VERSION"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE/ngspice:$NGSPICE_TAG"
    # Check if this version already exists
    - |
      if docker manifest inspect $IMAGE_NAME >/dev/null 2>&1 && [ "$FORCE_REBUILD" != "true" ]; then
        echo "ngspice $NGSPICE_VERSION already built, syncing latest tag (remote)"
        docker buildx imagetools create --tag "$CI_REGISTRY_IMAGE/ngspice:latest" "$IMAGE_NAME"
        exit 0
      fi
    - git clone --depth=1 --single-branch --branch=$NGSPICE_VERSION --filter=blob:none https://git.code.sf.net/p/ngspice/ngspice.git ngspice || exit 1
    - docker build --build-context ngspice-src=ngspice --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:latest -t $IMAGE_NAME -f docker/Dockerfile.ngspice .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/ngspice:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/ngspice:latest

# KiCad libraries - rebuild on schedule or manual
build-libs:
  <<: *dependency_rules
  script:
    - LIBS_DATE=$(date +%Y%m%d)
    - LIBS_TAG="libs-$LIBS_DATE"
        echo "Libraries for $LIBS_DATE already built, syncing latest tag (remote)"
        docker buildx imagetools create --tag "$CI_REGISTRY_IMAGE/libs:latest" "$IMAGE_NAME"
        exit 0
      fi
    # Libraries change frequently, rebuild on schedule
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-symbols.git symbols || exit 1
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-footprints.git footprints || exit 1
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-templates.git templates || exit 1
    - docker build
      --build-context symbols-src=symbols
      --build-context footprints-src=footprints
      --build-context templates-src=templates
      --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:latest -t $IMAGE_NAME -f docker/Dockerfile.libs .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/libs:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/libs:latest

# 3D packages - rebuild on schedule or manual
build-packages3d:
  <<: *dependency_rules
  script:
    - PACKAGES_DATE=$(date +%Y%m%d)
    - PACKAGES_TAG="packages3d-$PACKAGES_DATE"
    - IMAGE_NAME="$CI_REGISTRY_IMAGE/packages3d:$PACKAGES_TAG"
    # Check if today's 3D packages are already built
    - |
      if docker manifest inspect $IMAGE_NAME >/dev/null 2>&1 && [ "$FORCE_REBUILD" != "true" ]; then
        echo "3D packages for $PACKAGES_DATE already built, syncing latest tag (remote)"
        docker buildx imagetools create --tag "$CI_REGISTRY_IMAGE/packages3d:latest" "$IMAGE_NAME"
        exit 0
      fi
    # 3D packages change frequently, rebuild on schedule
    - git clone --depth=1 https://gitlab.com/kicad/libraries/kicad-packages3D.git packages3d || exit 1
    - docker build --build-context packages3d-src=packages3d --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/base:latest -t $IMAGE_NAME -f docker/Dockerfile.packages3d .
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE/packages3d:latest
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/packages3d:latest

# Final KiCad build - uses all pre-built dependencies
build-kicad:
  stage: build
  before_script:
    # Install dependencies
    - apk update && apk add --no-cache patch git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker context create ki-builder
    - docker buildx create ki-builder --driver docker-container --use
    - docker buildx inspect --bootstrap
    # Pull all dependency images
    - docker pull $CI_REGISTRY_IMAGE/base:latest
    - docker pull $CI_REGISTRY_IMAGE/wx:latest
    - docker pull $CI_REGISTRY_IMAGE/wxpython:latest
    - docker pull $CI_REGISTRY_IMAGE/ngspice:latest
    - docker pull $CI_REGISTRY_IMAGE/occt:latest
    - docker pull $CI_REGISTRY_IMAGE/libs:latest
    - docker pull $CI_REGISTRY_IMAGE/packages3d:latest
  script:
    - echo "CI_REGISTRY_IMAGE is '$CI_REGISTRY_IMAGE'"
    - echo "Registry arg will be '$CI_REGISTRY_IMAGE'"
    - git clone --branch=${KICAD_BRANCH:-master} --single-branch --depth=1 --filter=blob:none https://gitlab.com/kicad/code/kicad.git || exit 1
    - git clone https://github.com/sethhillbrand/appimage-builder.git && git --work-tree=./appimage-builder --git-dir=./appimage-builder/.git checkout fix-packaging-version-parse || exit 1
    - docker buildx build
      --progress=plain --build-context kicad-src=kicad
      --build-context appimage-builder-src=appimage-builder
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
      --build-arg KICAD_BUILD_RELEASE=${KICAD_BUILD_RELEASE}
      --build-arg KICAD_BUILD_MAJVERSION=${KICAD_BUILD_MAJVERSION}
      --build-arg KICAD_BUILD_TYPE=${KICAD_BUILD_TYPE}
      --platform linux/amd64
      --target build-kicad
      --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/cache:buildcache,mode=max
      --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/cache:buildcache
      -o type=local,dest=.
      -f Dockerfile .
  artifacts:
    paths:
      - '*.AppImage'

build-kicad-light:
  rules:
    - when: on_success
      needs: ["build-kicad"]
  stage: build
  before_script:
    # Install dependencies
    - apk update && apk add --no-cache patch git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker context create ki-builder
    - docker buildx create ki-builder --driver docker-container --use
    - docker buildx inspect --bootstrap
    # Pull all dependency images
    - docker pull $CI_REGISTRY_IMAGE/base:latest
    - docker pull $CI_REGISTRY_IMAGE/wx:latest
    - docker pull $CI_REGISTRY_IMAGE/wxpython:latest
    - docker pull $CI_REGISTRY_IMAGE/ngspice:latest
    - docker pull $CI_REGISTRY_IMAGE/occt:latest
    - docker pull $CI_REGISTRY_IMAGE/libs:latest
  script:
    - echo "CI_REGISTRY_IMAGE is '$CI_REGISTRY_IMAGE'"
    - echo "Registry arg will be '$CI_REGISTRY_IMAGE'"
    - git clone --branch=${KICAD_BRANCH:-master} --single-branch --depth=1 --filter=blob:none https://gitlab.com/kicad/code/kicad.git || exit 1
    - git clone https://github.com/sethhillbrand/appimage-builder.git && git --work-tree=./appimage-builder --git-dir=./appimage-builder/.git checkout fix-packaging-version-parse || exit 1
    - docker buildx build
      --progress=plain --build-context kicad-src=kicad
      --build-context appimage-builder-src=appimage-builder
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
      --build-arg KICAD_BUILD_RELEASE=${KICAD_BUILD_RELEASE}
      --build-arg KICAD_BUILD_MAJVERSION=${KICAD_BUILD_MAJVERSION}
      --build-arg KICAD_BUILD_TYPE=${KICAD_BUILD_TYPE}
      --platform linux/amd64
      --target build-kicad-light
      --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/cache:buildcache
      -o type=local,dest=.
      -f Dockerfile .
  artifacts:
    paths:
      - '*.AppImage'

upload-kicad:
  <<: *base_rules
  stage: upload
  needs:
    - job: build-kicad
      artifacts: true
    - job: build-kicad-light
      artifacts: true
  image: alpine:latest
  services: []
  before_script:
    - apk add --no-cache s3cmd
  script:
    - for f in *.AppImage; do \
        s3cmd put --host s3.cern.ch --host-bucket '%(bucket)s.s3.cern.ch' \
          --access_key="$S3_ACCESS_KEY" --secret_key="$S3_SECRET_KEY" \
          "$f" "s3://kicad-downloads/$BUCKET_OUTPUT_PATH/"; \
      done